# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Label remover
on:  
  push:
  pull_request:
    branches:
      - main

jobs:
  label_remover:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        if: contains( github.event.pull_request.labels.*.name, 'Ready')
        with:
          labels: Ready
